version: "3.9"

x-kong-config: &kong-env
  KONG_DATABASE: off
  KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_ADMIN_LISTEN: 0.0.0.0:8001
  KONG_ADMIN_GUI_URL: http://localhost:8899
  KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8899
  KONG_PLUGINS: bundled,oidc

services:
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    environment:
      <<: *kong-env
    ports:
      - "${KONG_PROXY_LISTEN:-0.0.0.0:8000}:8000"
      - "${KONG_PROXY_LISTEN:-0.0.0.0:8443}:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
      - "127.0.0.1:8899:8899"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    volumes:
      - ./kong.yaml:/opt/kong/kong.yaml:ro
    networks:
      - kong-net
      - martapi-net

  specs-combiner:
    build:
      context: ./specs-combiner
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - kong-net
      - martapi-net

networks:
  kong-net:
    driver: bridge
  martapi-net:
    external: true
